### ISSUE TITLE
libpocketsphinx.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vowers** [wzpan/dingdang-robot#137]
2018-03-15 22:17:57,042 dingdang.py[line:175]             ERROR Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 173, in <module>
    app = Dingdang()
  File "dingdang.py", line 95, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/data/dingdang/client/stt.py", line 66, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/data/dingdang/client/stt.py", line 60, in get_instance
    instance = cls(**config)
  File "/home/pi/data/dingdang/client/stt.py", line 116, in __init__
    import pocketsphinx as ps
ImportError: libpocketsphinx.so.1: cannot open shared object file: No such file or directory

**Comment by wzpan** [comment]
duplicate #95
