### ISSUE TITLE
无法唤醒报错

### ISSUE THREAD

**Issue by ji3g4bp6x** [wzpan/dingdang-robot#69]
Traceback (most recent call last):
  File "dingdang.py", line 228, in <module>
    app.run()
  File "dingdang.py", line 181, in run
    self.mic.say(salutation)
  File "/home/pi/dingdang/client/mic.py", line 340, in say
    self.speaker.say(phrase)
  File "/home/pi/dingdang/client/tts.py", line 587, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 579, in get_speech
    r = requests.get(voice_url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='proxy.peiyinge.com', port=17063): Max retries exceeded with url: /synth?ts=1510863836&sign=291f287a7dbb784bc0aa35b4e3828406&vid=65360&volume=&speed=0&content=%E4%BC%9F%E6%B4%B2%20%E6%88%91%E8%83%BD%E4%B8%BA%E6%82%A8%E5%81%9A%E4%BB%80%E4%B9%88%3F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73fb6410>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by wzpan** [comment]
你用的是自带的科大讯飞id和key，太多人用同一个所以超出了当日使用限制了。自己申请一个吧。
