### ISSUE TITLE
请教dalao

### ISSUE THREAD

**Issue by zanjie1999** [wzpan/dingdang-robot#70]
运行 dingdang.py 抛出异常
```
Traceback (most recent call last):
  File "dingdang.py", line 12, in <module>
    from client import stt
  File "/home/sparkle/dingdang-robot/client/stt.py", line 22, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning
```
用 pip 安装 requests 结果一样

另外编译安装 Phonetisaurus 时,make各种报错编译失败

均严格按照文档操作

**Comment by wzpan** [comment]
wiki 常见问题有解答。

另外文档提供的是 Raspbian 系统下的手动安装方法，未在其他操作系统上测试。使用其他操作系统的请自行根据出错提示解决问题。

**Comment by zanjie1999** [comment]
补充: 系统是dietpi
