### ISSUE TITLE
按照教程安装的，出错了，这是什么原因

### ISSUE THREAD

**Issue by Cdmoonb** [wzpan/dingdang-robot#94]
2018-01-04 11:54:24,954 vocabcompiler.py[line:161]             INFO Starting compilation...
2018-01-04 11:54:24,960 vocabcompiler.py[line:166]             ERROR Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/chenpeng/dingdang/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/chenpeng/dingdang/client/vocabcompiler.py", line 269, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/chenpeng/dingdang/client/vocabcompiler.py", line 290, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 485, in text2vocab
    text2wfreq(text, wfreq_file, **text2wfreq_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 114, in text2wfreq
    raise ConversionError("'%s' returned with non-zero exit status '%s'" % (cmd[0], exitcode))
ConversionError: 'text2wfreq' returned with non-zero exit status '127'
2018-01-04 11:54:24,960 dingdang.py[line:174]             ERROR Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 172, in <module>
    app = Dingdang()
  File "dingdang.py", line 94, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/chenpeng/dingdang/client/stt.py", line 59, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/chenpeng/dingdang/client/stt.py", line 51, in get_instance
    vocabulary.compile(phrases)
  File "/home/chenpeng/dingdang/client/vocabcompiler.py", line 171, in compile
    raise e
ConversionError: 'text2wfreq' returned with non-zero exit status '127'

**Comment by Cdmoonb** [comment]
vocabularies装错位置了
